### ISSUE TITLE
Implement index tracker

### ISSUE THREAD

**Issue by georgbuechner** [georgbuechner/litt#15]
The methods of the index tracker should be properly implemented, this includes:
- finding a json/ yaml library
- #8 
- adding an index to config (name, path)
- getting `path` from `name`
- checking if `name` and/ or `path` already exists

**Comment by SimonThormeyer** [comment]
@georgbuechner I prefer json in general, I think parsing json is faster, but not sure.
A reason to take yaml could be that it's nicer to look at for some, or that it supports comments.
I'm fine with either because none of the two reasons really matters a lot in our case
